import{S as q,a as v,i as n}from"./assets/vendor-DZWlGVzj.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))u(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const g of r.addedNodes)g.tagName==="LINK"&&g.rel==="modulepreload"&&u(g)}).observe(document,{childList:!0,subtree:!0});function a(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function u(t){if(t.ep)return;t.ep=!0;const r=a(t);fetch(t.href,r)}})();let c;function M(e){return`
        <li class="gallery-item">
            <a href="${e.largeImageURL}" class="gallery-link">
                <img src="${e.webformatURL}" alt="${e.tags}" class="gallery-image" loading="lazy" />
            </a>
            <ul class="gallery-info">
                <li class="gallery-info-item"><p>Likes</p><span>${e.likes}</span></li>
                <li class="gallery-info-item"><p>Views</p><span>${e.views}</span></li>
                <li class="gallery-info-item"><p>Comments</p><span>${e.comments}</span></li>
                <li class="gallery-info-item"><p>Downloads</p><span>${e.downloads}</span></li>
            </ul>
        </li>
    `}function y(e){return e.map(M).join("")}function p(){return c||(c=new q(".gallery-link",{captionsData:"alt",captionDelay:250})),c}function x(e){const o=document.querySelector(".gallery");if(!o)return;o.innerHTML=y(e),p().refresh()}function B(e){const o=document.querySelector(".gallery");if(!o)return;o.insertAdjacentHTML("beforeend",y(e)),p().refresh()}function I(){const e=document.querySelector(".gallery");e&&(e.innerHTML=""),c&&c.refresh()}function L(){const e=document.querySelector(".load-message");e&&e.classList.remove("is-hidden")}function b(){const e=document.querySelector(".load-message");e&&e.classList.add("is-hidden")}function h(e,o){e<o?P():d()}function P(){const e=document.querySelector(".loader-btn");e&&(e.classList.remove("is-hidden"),e.disabled=!1)}function d(){const e=document.querySelector(".loader-btn");e&&(e.classList.add("is-hidden"),e.disabled=!0)}const D=v.create({baseURL:"https://pixabay.com/api/"}),w=async(e,o)=>(await D.get("",{params:{key:"55965686-0954e8ecbc9e6337c09710879",q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:15}})).data,m=document.querySelector(".form"),E=document.querySelector(".loader-btn"),i=document.querySelector(".load-message"),S=15;let s=1,f="",l=0;m.addEventListener("submit",e=>{var t;e.preventDefault();const a=(t=new FormData(m).get("search-text"))==null?void 0:t.trim();if(!a){n.warning({title:"Warning",message:"Please enter a search term!"});return}I(),d(),L(),i&&i.classList.remove("is-hidden");const u=async()=>{try{s=1,f=a;const r=await w(f,s);if(!r.hits||r.hits.length===0){n.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"});return}x(r.hits),l=Math.ceil(r.totalHits/S),h(s,l),s>=l&&(d(),n.info({title:"Info",message:"We're sorry, but you've reached the end of search results."}))}catch(r){console.error(r),n.error({title:"Error",message:"Something went wrong while loading images."})}finally{b(),i&&i.classList.add("is-hidden")}};m.reset(),u()});E.addEventListener("click",async()=>{if(f){d(),L(),i&&i.classList.remove("is-hidden");try{s+=1;const e=await w(f,s);if(!e.hits||e.hits.length===0){n.error({title:"Error",message:"No more images available. Please try a different query."}),s-=1;return}B(e.hits);const o=document.querySelector(".gallery-item");if(o){const a=o.getBoundingClientRect().height;window.scrollBy({top:a*2,behavior:"smooth"})}l=Math.ceil(e.totalHits/S),s>=l?(d(),n.info({title:"Info",message:"We're sorry, but you've reached the end of search results."})):h(s,l)}catch(e){console.error(e),n.error({title:"Error",message:"Something went wrong while loading images."}),s-=1,h(s,l)}finally{b(),i&&i.classList.add("is-hidden")}}});
//# sourceMappingURL=index.js.map
