import{S,a as q,i as n}from"./assets/vendor-DZWlGVzj.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))c(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const f of r.addedNodes)f.tagName==="LINK"&&f.rel==="modulepreload"&&c(f)}).observe(document,{childList:!0,subtree:!0});function s(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function c(t){if(t.ep)return;t.ep=!0;const r=s(t);fetch(t.href,r)}})();let l;function v(e){return`
        <li class="gallery-item">
            <a href="${e.largeImageURL}" class="gallery-link">
                <img src="${e.webformatURL}" alt="${e.tags}" class="gallery-image" loading="lazy" />
            </a>
            <ul class="gallery-info">
                <li class="gallery-info-item"><p>Likes</p><span>${e.likes}</span></li>
                <li class="gallery-info-item"><p>Views</p><span>${e.views}</span></li>
                <li class="gallery-info-item"><p>Comments</p><span>${e.comments}</span></li>
                <li class="gallery-info-item"><p>Downloads</p><span>${e.downloads}</span></li>
            </ul>
        </li>
    `}function m(e){return e.map(v).join("")}function y(){return l||(l=new S(".gallery-link",{captionsData:"alt",captionDelay:250})),l}function M(e){const o=document.querySelector(".gallery");if(!o)return;o.innerHTML=m(e),y().refresh()}function x(e){const o=document.querySelector(".gallery");if(!o)return;o.insertAdjacentHTML("beforeend",m(e)),y().refresh()}function B(){const e=document.querySelector(".gallery");e&&(e.innerHTML=""),l&&l.refresh()}function h(){const e=document.querySelector(".load-message");e&&e.classList.remove("is-hidden")}function p(){const e=document.querySelector(".load-message");e&&e.classList.add("is-hidden")}function b(e,o){e<o?I():u()}function I(){const e=document.querySelector(".loader-btn");e&&(e.classList.remove("is-hidden"),e.disabled=!1)}function u(){const e=document.querySelector(".loader-btn");e&&(e.classList.add("is-hidden"),e.disabled=!0)}const P=q.create({baseURL:"https://pixabay.com/api/"}),L=async(e,o)=>(await P.get("",{params:{key:"55965686-0954e8ecbc9e6337c09710879",q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:15}})).data,g=document.querySelector(".form"),D=document.querySelector(".loader-btn");document.querySelector(".load-message");const w=15;let a=1,d="",i=0;g.addEventListener("submit",e=>{var t;e.preventDefault();const s=(t=new FormData(g).get("search-text"))==null?void 0:t.trim();if(!s){n.warning({title:"Warning",message:"Please enter a search term!"});return}B(),u(),h();const c=async()=>{try{a=1,d=s;const r=await L(d,a);if(!r.hits||r.hits.length===0){n.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"});return}M(r.hits),i=Math.ceil(r.totalHits/w),b(a,i),a>=i&&(u(),n.info({title:"Info",message:"We're sorry, but you've reached the end of search results."}))}catch(r){console.error(r),n.error({title:"Error",message:"Something went wrong while loading images."})}p()};g.reset(),c()});D.addEventListener("click",async()=>{if(d){h();try{a+=1;const e=await L(d,a);if(!e.hits||e.hits.length===0){n.error({title:"Error",message:"No more images available. Please try a different query."}),a-=1;return}x(e.hits);const o=document.querySelector(".gallery-item");if(o){const s=o.getBoundingClientRect().height;window.scrollBy({top:s*2,behavior:"smooth"})}i=Math.ceil(e.totalHits/w),a>=i?(u(),n.info({title:"Info",message:"We're sorry, but you've reached the end of search results."})):b(a,i)}catch(e){console.error(e),n.error({title:"Error",message:"Something went wrong while loading images."}),a-=1}p()}});
//# sourceMappingURL=index.js.map
